services:
  postgres:
    image: postgres:16-alpine
    container_name: argenprop-db
    environment:
      POSTGRES_USER: argenprop
      POSTGRES_PASSWORD: argenprop
      POSTGRES_DB: argenprop
    ports:
      - "5434:5432"
    volumes:
      - argenprop_pgdata:/var/lib/postgresql/data

volumes:
  argenprop_pgdata:
